
% This is a sample main file that reads two grayordinate fmri files generated by bfp and outputs the synced files.

clc;clear all;close all;
addpath(genpath('/home/ajoshi/coding_ground/svreg'));
addpath(genpath('../'));

sl=readdfs('/home/ajoshi/coding_ground/bfp/supp_data/bci32kleft.dfs');
sl=smooth_cortex_fast(sl,.1,1500);
sr=readdfs('/home/ajoshi/coding_ground/bfp/supp_data/bci32kright.dfs');
sr=smooth_cortex_fast(sr,.1,1500);

subid='sn7602';
subl=readdfs(['/home/ajoshi/coding_ground/brainsync/src/left_pval_',subid,'.dfs']);
subr=readdfs(['/home/ajoshi/coding_ground/brainsync/src/right_pval_',subid,'.dfs']);
subr.vertices = sr.vertices;
subl.vertices = sl.vertices;

h=figure;
patch('faces',subr.faces,'vertices',subr.vertices,'facevertexcdata',subr.attributes,'facecolor','interp','edgecolor','none');
view(90,0);axis equal;axis off;camlight;material dull;caxis([0,0.05]);colormap jet;
saveas(h,['right_pval_',subid,'_LB80_1_new.png']);
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,0.05]);colormap jet;
saveas(h,['right_pval_',subid,'_LB80_2_new.png']);

h=figure;
patch('faces',subl.faces,'vertices',subl.vertices,'facevertexcdata',subl.attributes,'facecolor','interp','edgecolor','none');
view(90,0);axis equal;axis off;camlight;material dull;caxis([0,0.05]);colormap jet;
saveas(h,['left_pval_',subid,'_LB80_1_new.png']);
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,0.05]);colormap jet;
saveas(h,['left_pval_',subid,'_LB80_2_new.png']);
