
% This is a sample main file that reads two grayordinate fmri files generated by bfp and outputs the synced files.

clc;clear all;close all;
addpath(genpath('/big_disk/ajoshi/coding_ground/bfp/'));
g1=ft_read_cifti('/big_disk/ajoshi/sample_from_andrew/100307/rfMRI_1_LR/rfMRI_1_LR_LNLM_p72.dtseries.nii');
g2=ft_read_cifti('/big_disk/ajoshi/sample_from_andrew/100307/rfMRI_2_LR/rfMRI_2_LR_LNLM_p72.dtseries.nii');


indL1=g1.brainstructure==1;
indL2=g2.brainstructure==1;
indR1=g1.brainstructure==2;
indR2=g2.brainstructure==2;

datL1=normalizeData(g1.dtseries(indL1,:)');
datL2=normalizeData(g2.dtseries(indL2,:)');
datR1=normalizeData(g1.dtseries(indR1,:)');
datR2=normalizeData(g2.dtseries(indR2,:)');

%g1.dtseries=g1.dtseries(1:32000,:);
%g2.dtseries=g2.dtseries(1:32000,:);

rho_beforeLR1=sum(datL1.*datR1,1);
rho_beforeLR2=sum(datL2.*datR2,1);

[dtseries_sync,R]=brainSync(datL1,datL2);
rho_afterL=sum(datL1.*dtseries_sync,1);
rho_afterR=sum(datR1.*(R*datR2),1);


fprintf('Correlation before=%g, after=%g,%g\n',mean(rho_before), mean(rho_after), mean(rho_afterR));

s=gifti('/big_disk/ajoshi/sample_from_andrew/common_anat/100307.L.midthickness.11k_fs_LR.surf.gii')
sR=gifti('/big_disk/ajoshi/sample_from_andrew/common_anat/100307.R.midthickness.11k_fs_LR.surf.gii')

patch('vertices',s.vertices,'faces',double(s.faces),'facevertexcdata',rho_after','edgecolor','none','facecolor','interp');
axis equal;axis off;camlight;material dull;colormap jet;

