
% This is a sample main file that reads two grayordinate fmri files generated by bfp and outputs the synced files.

clc;clear all;close all;
addpath(genpath('../'));
g1=load('/NCAdisk/SCD_structural_analysis/BOLD_study/SCD_BOLDdata/ACTL004/func/ACTL004_rest_bold.32k.GOrd.filt.mat');
g2=load('/home/sychoi/Dropbox/SCD/Analysis/BOLD/092719/atlas.mat');
sl=readdfs('/home/ajoshi/coding_ground/bfp/supp_data/bci32kleft.dfs');
msk=load('/big_disk/ajoshi/HCP100-fMRI-NLM/HCP100-fMRI-NLM/reference/100307.LR_mask.mat');


g1.dtseries=normalizeData(g1.dtseries')';
g2.dtseries=normalizeData(g2.dtseries')';

rho_before=sum(g1.dtseries.*g2.dtseries,2);
dtseries_sync=brainSync(g1.dtseries',g2.dtseries')';
rho_after=sum(g1.dtseries.*dtseries_sync,2);
fprintf('Correlation before=%g, after=%g\n',mean(rho_before), mean(rho_after));


cSZ=length(msk.LR_flag);
g1.dtseries=g1.dtseries(1:cSZ,:);
g2.dtseries=g2.dtseries(1:cSZ,:);

g1.dtseries=g1.dtseries(msk.LR_flag,:);
g2.dtseries=g2.dtseries(msk.LR_flag,:);

% This code computes laplace beltrami operator matrix and stores it. Do this once.
% LBO = getLaplaceBeltramiOperator(sl,.1);
% aa=toc(a)
% save LBO LBO
load LBO
g1.dtseries = laplaceBeltramiSmooth(LBO, g1.dtseries, 20);
g2.dtseries = laplaceBeltramiSmooth(LBO, g2.dtseries, 20);

g1.dtseries=normalizeData(g1.dtseries')';
g2.dtseries=normalizeData(g2.dtseries')';

rho_before=sum(g1.dtseries.*g2.dtseries,2);
figure;
patch('faces',sl.faces,'vertices',sl.vertices,'facevertexcdata',rho_before,'facecolor','interp','edgecolor','none');
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);

dtseries_sync=brainSync(g1.dtseries',g2.dtseries')';
rho_after=sum(g1.dtseries.*dtseries_sync,2);
fprintf('Correlation before=%g, after=%g\n',mean(rho_before), mean(rho_after));

figure;
patch('faces',sl.faces,'vertices',sl.vertices,'facevertexcdata',rho_after,'facecolor','interp','edgecolor','none');
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);

