
% This is a sample main file that reads two grayordinate fmri files generated by bfp and outputs the synced files.

clc;clear all;close all;
addpath(genpath('/home/ajoshi/coding_ground/svreg'));
addpath(genpath('../'));
g2=load('/home/ajoshi/Downloads/sub10186/func/sub10186_rest_bold.32k.GOrd.mat');
g1=load('/home/ajoshi/Downloads/sub10973/func/sub10973_rest_bold.32k.GOrd.mat');
g2.dtseries=g2.dtseries(:,1:196);
g2=load('/deneb_disk/from_Todd_Constable_Epilepsy_Processed/sn7602/func/sn7602_rest_bold.32k.GOrd.mat');
sl=readdfs('/home/ajoshi/coding_ground/bfp/supp_data/bci32kleft.dfs');
sl=smooth_cortex_fast(sl,.1,3000);
sr=readdfs('/home/ajoshi/coding_ground/bfp/supp_data/bci32kright.dfs');
sr=smooth_cortex_fast(sr,.1,3000);
msk=load('/big_disk/ajoshi/HCP100-fMRI-NLM/HCP100-fMRI-NLM/reference/100307.LR_mask.mat');

g1.dtseries=g1.dtseries(:,1:size(g2.dtseries,2));
g1.dtseries=normalizeData(g1.dtseries')';
g2.dtseries=normalizeData(g2.dtseries')';

rho_before=sum(g1.dtseries.*g2.dtseries,2);
dtseries_sync=brainSync(g1.dtseries',g2.dtseries')';
rho_after=sum(g1.dtseries.*dtseries_sync,2);
fprintf('Correlation before=%g, after=%g\n',mean(rho_before), mean(rho_after));


cSZ=length(msk.LR_flag);
g1.dtseries=g1.dtseries(1:cSZ,:);
g2.dtseries=g2.dtseries(1:cSZ,:);

g1o=g1;g2o=g2;

g1.dtseries=g1.dtseries(msk.LR_flag,:);
g2.dtseries=g2.dtseries(msk.LR_flag,:);

% This code computes laplace beltrami operator matrix and stores it. Do this once.
% LBO = getLaplaceBeltramiOperator(sl,.1);
% aa=toc(a)
% save LBO_left LBO
% LBO = getLaplaceBeltramiOperator(sr,.1);
% aa=toc(a)
% save LBO_right LBO

load LBO_left
g1.dtseries = laplaceBeltramiSmooth(LBO, g1.dtseries, 80);
g2.dtseries = laplaceBeltramiSmooth(LBO, g2.dtseries, 80);

g1.dtseries=normalizeData(g1.dtseries')';
g2.dtseries=normalizeData(g2.dtseries')';
rho_before=sum(g1.dtseries.*g2.dtseries,2);
figure;
patch('faces',sl.faces,'vertices',sl.vertices,'facevertexcdata',rho_before,'facecolor','interp','edgecolor','none');
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);

dtseries_sync=brainSync(g1.dtseries',g2.dtseries')';
rho_after=sum(g1.dtseries.*dtseries_sync,2);
fprintf('Correlation before=%g, after=%g\n',mean(rho_before), mean(rho_after));
figure;
patch('faces',sl.faces,'vertices',sl.vertices,'facevertexcdata',rho_after,'facecolor','interp','edgecolor','none');
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);colormap jet;



%Right Hemisphere
g1.dtseries=g1o.dtseries(msk.LR_flag==0,:);
g2.dtseries=g2o.dtseries(msk.LR_flag==0,:);

load LBO_right
g1.dtseries = laplaceBeltramiSmooth(LBO, g1.dtseries, 40);
g2.dtseries = laplaceBeltramiSmooth(LBO, g2.dtseries, 40);

g1.dtseries=normalizeData(g1.dtseries')';
g2.dtseries=normalizeData(g2.dtseries')';

rho_before=sum(g1.dtseries.*g2.dtseries,2);

figure;
patch('faces',sr.faces,'vertices',sr.vertices,'facevertexcdata',rho_before,'facecolor','interp','edgecolor','none');
view(-90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);

dtseries_sync=brainSync(g1.dtseries',g2.dtseries')';
rho_after=sum(g1.dtseries.*dtseries_sync,2);
fprintf('Correlation before=%g, after=%g\n',mean(rho_before), mean(rho_after));

figure;
patch('faces',sr.faces,'vertices',sr.vertices,'facevertexcdata',rho_after,'facecolor','interp','edgecolor','none');
view(90,0);axis equal;axis off;camlight;material dull;caxis([0,1]);colormap jet;


