# coding: utf-8

# # Regression Pipeline

# This notebook serves as a template for performing a group difference comparison using BFP and BrainSync. The steps in this pipeline can be easily customized to suite your study. Here, we use data from ADHD200 dataset available through http://fcon_1000.projects.nitrc.org/indi/adhd200/. Specifically, we use the Peking dataset. We will correlate cognitive score and fmri signal deviation from normals. This will find the areas that are associated with fMRI signal.
#
# The pipeline is written in Python (Jupyter Notebook). We assume thet BrainSuite and BFP are installed on your computer. Install the required python libraries listed below in the script. We recommend using Anaconda python distribution.
#
# The steps for running the group comparison are:
#
# * Process the fMRI and T1 data of subjects using BFP.
# * Set the paths in group analysis script.
# * Run the regression script.
#
# As an input, we assume that all the subjects data has been preprocessed using BFP. Specifically, we will use the grayordinate data produced by BFP. Also a CSV file containing group labels is assume as an input.
#
# First, we use a set of normal control subjects to build an average atlas. Currently, it is done by using BrainSync to synchronize all subject data to an individual and then averaging the synchronized data. In the future, we can use group brainsync included in BFP.
#
# For a population of subjects, we will compute correlation between norm of synchronized fMRI signal of subjects and atlas, and the cognitive scores of the subjects.
#
# In the future, we will compute multivariate regression.
#
# ### Import the required libraries

# In[1]:

import scipy.io as spio
import scipy as sp
import numpy as np
from surfproc import view_patch_vtk, patch_color_attrib, smooth_surf_function, smooth_patch
from dfsio import readdfs
import os
from brainsync import normalizeData, brainSync
from sklearn.decomposition import PCA
import statsmodels.api as sm
from statsmodels.stats.multitest import fdrcorrection
from stats_utils import read_fcon1000_data
# ### Set the directories for the data and BFP software
from tqdm import tqdm

# In[2]:

BFPPATH = '/home/ajoshi/coding_ground/bfp'
NDIM = 200  # Dimensionality reduction for analysis

# study directory where all the grayordinate files lie
DATA_DIR = '/deneb_disk/ADHD_Peking_gord'
CSV_FILE = '/deneb_disk/ADHD_Peking_bfp/Peking_all_phenotypic.csv'

# ### Read CSV file to read the group IDs. This study has three subgroups:
# 1. Normal controls,
# 2. ADHD-hyperactive, and
# 3. ADHD-inattentive.

NUM_SUB_ATLAS = 50  # number of subjects for atlas creation
LEN_TIME = 235  # length of the time series
NUM_SUB = 150  # Number of subjects for the study


def main():

    # Read NUM_SUB_ATLAS subjects for creating the atlas
    sub_ids, reg_var, sub_data = read_fcon1000_data(
        csv_fname=CSV_FILE,
        data_dir=DATA_DIR,
        reg_var_name='Verbal IQ',
        num_sub=NUM_SUB_ATLAS,
        len_time=LEN_TIME)

    # ### Generate average subject
    # An atlas is generated by synchronizing all normal subject's data to one subject.

    # Create Average atlas by synchronizing everyones data to one subject
    q = 3
    for ind in tqdm(range(NUM_SUB_ATLAS)):
        Y2, _ = brainSync(X=sub_data[:, :, q], Y=sub_data[:, :, ind])
        if ind == 0:
            avg_atlas = Y2
        else:
            avg_atlas += Y2

    avg_atlas /= (NUM_SUB_ATLAS)
    spio.savemat('avg_atlas.mat', {'avg_atlas': avg_atlas})

    print('Atlas computed and saved')
    # ### Learn PCA basis
    # Compute PCA basis function from the atlas and use it for dimensionality reduction of the data.
    pca = PCA(n_components=NDIM)
    pca.fit(avg_atlas.T)
    print(pca.explained_variance_ratio_)

    # Read normal control subjects for statistical testing
    print('Reading subjects')

    sub_ids, reg_var, sub_data = read_fcon1000_data(
        csv_fname=CSV_FILE,
        data_dir=DATA_DIR,
        reg_var_name='Verbal IQ',
        num_sub=NUM_SUB,
        len_time=LEN_TIME)

    print(
        'Synchronize the subject data to the atlas and perform PCA of the result'
    )
    print(
        'Then compute difference between atlas and the subject. This is the test statistic.'
    )

    diff = sp.zeros([sub_data.shape[1], NUM_SUB])
    rData = sp.zeros((NDIM, sub_data.shape[1], NUM_SUB))

    for ind in tqdm(range(NUM_SUB)):
        Y2, _ = brainSync(X=avg_atlas, Y=sub_data[:, :, ind])
        rData[:, :, ind] = pca.transform(Y2.T).T
        diff[:, ind] = sp.sum((Y2 - avg_atlas)**2, axis=0)

    spio.savemat('diff_avg_atlas.mat', {'diff': diff})

    # In[9]:

    rcorr = sp.zeros(diff.shape[0])
    r = sp.array(reg_var[:NUM_SUB])
    r = sp.absolute(r - sp.mean(r))
    pval_surf = sp.zeros(diff.shape[0])

    for nv in range(diff.shape[0]):
        a = sp.corrcoef(diff[nv, :], r)
        rcorr[nv] = a[0, 1]

        X = rData[:, nv, :]
        X = sm.add_constant(X.T)
        est = sm.OLS(r, X)
        pval_surf[nv] = est.fit().f_pvalue

    print('Regression is done')

    m = np.isnan(pval_surf)
    pval_surf[m] = .5
    _, pval_surf_corr = fdrcorrection(pval_surf)
    #  ### Read surfaces for visualization

    # In[12]:

    lsurf = readdfs(BFPPATH + '/supp_data/bci32kleft.dfs')
    rsurf = readdfs(BFPPATH + '/supp_data/bci32kright.dfs')
    a = spio.loadmat(BFPPATH + '/supp_data/USCBrain_grayord_labels.mat')
    labs = a['labels']

    lsurf.attributes = np.zeros((lsurf.vertices.shape[0]))
    rsurf.attributes = np.zeros((rsurf.vertices.shape[0]))
    lsurf = smooth_patch(lsurf, iterations=1500)
    rsurf = smooth_patch(rsurf, iterations=1500)
    labs[sp.isnan(labs)] = 0
    print(rcorr.shape, labs.shape)
    rcorr = rcorr * (labs > 0)

    nVert = lsurf.vertices.shape[0]

    # ### Visualize the norm of the difference of Normal Controls from the atlas, at each point on the cortical surface

    # In[13]:

    lsurf.attributes = rcorr.squeeze()
    lsurf.attributes = lsurf.attributes[:nVert]
    rsurf.attributes = rcorr.squeeze()
    rsurf.attributes = rsurf.attributes[nVert:2 * nVert]
    lsurf = patch_color_attrib(lsurf, clim=[-.5, .5])
    rsurf = patch_color_attrib(rsurf, clim=[-.5, .5])
    print(lsurf.attributes.shape, nVert, lsurf.vColor.shape)
    view_patch_vtk(
        lsurf,
        azimuth=100,
        elevation=180,
        roll=90,
        outfile='l1corr.png',
        show=1)
    view_patch_vtk(
        rsurf,
        azimuth=-100,
        elevation=180,
        roll=-90,
        outfile='r1corr.png',
        show=1)

    # ### Visualize the norm of the difference of ADHD from the atlas

    # ### All Done!! The outputs are saved as png files.

    lsurf.attributes = 0.05 - pval_surf_corr.squeeze()
    lsurf.attributes = lsurf.attributes[:nVert]
    rsurf.attributes = 0.05 - pval_surf_corr.squeeze()
    rsurf.attributes = rsurf.attributes[nVert:2 * nVert]
    lsurf = patch_color_attrib(lsurf, clim=[0, .05])
    rsurf = patch_color_attrib(rsurf, clim=[0, .05])
    print(lsurf.attributes.shape, nVert, lsurf.vColor.shape)
    view_patch_vtk(
        lsurf,
        azimuth=100,
        elevation=180,
        roll=90,
        outfile='l1_pval.png',
        show=1)
    view_patch_vtk(
        rsurf,
        azimuth=-100,
        elevation=180,
        roll=-90,
        outfile='r1_pavl.png',
        show=1)

    # ### Visualize the norm of the difference of ADHD from the atlas
    lsurf = patch_color_attrib(lsurf, clim=[0, .5])
    rsurf = patch_color_attrib(rsurf, clim=[0, .5])
    print(lsurf.attributes.shape, nVert, lsurf.vColor.shape)
    view_patch_vtk(
        lsurf,
        azimuth=100,
        elevation=180,
        roll=90,
        outfile='l1_pval_p5.png',
        show=1)
    view_patch_vtk(
        rsurf,
        azimuth=-100,
        elevation=180,
        roll=-90,
        outfile='r1_pavl_p5.png',
        show=1)

    print('Saving results')
    spio.savemat(
        'iq_reg_res.mat', {
            'lsurf': lsurf,
            'rsurf': rsurf,
            'pval_surf': pval_surf,
            'pval_surf_corr': pval_surf_corr
        })

    print('Results saved')


if __name__ == "__main__":
    main()